name: implementing cicd pipeline

on:
  push:
    branches: [main]
  #workflow_dispatch:
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    - name: compile code
      run: mvn compile
